# Generated by Django 3.1.5 on 2021-02-01 06:11

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Tutorial_Category',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tut_category', models.CharField(max_length=200)),
                ('tut_summary', models.TextField()),
            ],
        ),
        migrations.CreateModel(
            name='Tutorial_Series',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tut_series', models.CharField(max_length=200)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('tut_category', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='tutorials.tutorial_category')),
            ],
        ),
        migrations.CreateModel(
            name='Tutorial',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tut_title', models.CharField(max_length=200)),
                ('tut_content', models.TextField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('tut_series', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='tutorials.tutorial_series')),
            ],
        ),
    ]
